language: cpp
sudo: required
dist: trusty

addons:
  coverity_scan:
    project:
      name: "device-simulator"
      description: "A generic tile map editor"
    notification_email: marlontrujillo1080@gmail.com
    build_command_prepend: qmake
    build_command: make
    branch_pattern: coverity_scan

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
        - sudo apt-get update -qq
        - sudo apt-get -y install qt59base qt59svg qt59imageformats qt59tools qt59qbs binutils zlib1g-dev
        - source /opt/qt59/bin/qt59-env.sh
        - sudo apt-get install tree
      script:
        - qmake --version
        - qmake device-simulator.pro -spec linux-g++
      after_success:
      after_failure:
      deploy:
        provider: releases
        api_key: "a28de0f82d18fd5bf96d0e630ac5e36c7a52a269"
        file: "./"
        skip_cleanup: true
        on:
          tags: true
